### ISSUE TITLE
helm部署的时候，grafana的initContainer出现报错日志: can't create directory '/var/lib/grafana/plugins/deepflow-apptracing-panel': No such file or directory...

### ISSUE THREAD

**Issue by liuxuzxx** [deepflowio/deepflow-gui-grafana#128]
1.  通过helm安装deepflow组件
2.  其他组件:clickhouse,mysql,app,server,agent都正常，但是grafana的initContainer出现错误日志如下:
```bash
cp: can't create directory '/var/lib/grafana/plugins/deepflow-apptracing-panel': No such file or directory
cp: can't create directory '/var/lib/grafana/plugins/deepflow-querier-datasource': No such file or directory
cp: can't create directory '/var/lib/grafana/plugins/deepflow-topo-panel': No such file or directory
cp: can't create directory '/var/lib/grafana/plugins/grafana-clickhouse-datasource': No such file or directory
```

目前我的临时解决方案是:

1. 修改如下配置
```yaml
---
apiVersion: apps/v1
...省略
spec:
  template:
    spec:
      initContainers:
        - image:  xwharbor.wxchina.com/cpaas/deepflow-ce/deepflowio-init-grafana:v7.0.4
        
          #1.增加挂载，这个点有点疑惑啊，pod内的container不是通过volumeMounts来共享文件系统的吗？之前都没有volumeMounts，如何共享的?
          volumeMounts:
            - mountPath: /var/lib/grafana/plugins
              name: custom-plugins
      #2.直接粗暴的给root级别的用户运行，先跑起来在说
      securityContext:
        runAsUser: 0


```
